// const randomListURL = "https://api.spotify.com/v1/recommendations?seed_artists=6WH1V41LwGDGmlPUhSZLHO&seed_genres=electronic&seed_tracks=33zDGjUK3BiqgFxoIpUWLy"

export const playlistData = [{"playlistName": "test 1", "list": 
{
    "seeds": [
      {
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "href": "https://api.spotify.com/v1/artists/6WH1V41LwGDGmlPUhSZLHO",
        "id": "6WH1V41LwGDGmlPUhSZLHO",
        "initialPoolSize": 500,
        "type": "ARTIST"
      },
      {
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "href": "https://api.spotify.com/v1/tracks/33zDGjUK3BiqgFxoIpUWLy",
        "id": "33zDGjUK3BiqgFxoIpUWLy",
        "initialPoolSize": 500,
        "type": "TRACK"
      },
      {
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "href": null,
        "id": "electronic",
        "initialPoolSize": 1000,
        "type": "GENRE"
      }
    ],
    "tracks": [
      {
        "album": {
          "album_type": "ALBUM",
          "total_tracks": 12,
          "available_markets": ["AD", "AE", "AG", "AL", "AM", "AO", "AR", "AT", "AU", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CD", "CG", "CH", "CI", "CL", "CM", "CO", "CR", "CV", "CW", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "ET", "FI", "FJ", "FM", "FR", "GA", "GB", "GD", "GE", "GH", "GM", "GN", "GQ", "GR", "GT", "GW", "GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IQ", "IS", "IT", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KR", "KW", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MN", "MO", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RW", "SA", "SB", "SC", "SE", "SG", "SI", "SK", "SL", "SM", "SN", "SR", "ST", "SV", "SZ", "TD", "TG", "TH", "TJ", "TL", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "UY", "UZ", "VC", "VE", "VN", "VU", "WS", "XK", "ZA", "ZM", "ZW"],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6UUJq06fTAr9H7xLiE1VFS"
          },
          "href": "https://api.spotify.com/v1/albums/6UUJq06fTAr9H7xLiE1VFS",
          "id": "6UUJq06fTAr9H7xLiE1VFS",
          "images": [
            {
              "url": "https://i.scdn.co/image/ab67616d0000b27392f9a000a881a5496fa62b6d",
              "height": 640,
              "width": 640
            },
            {
              "url": "https://i.scdn.co/image/ab67616d00001e0292f9a000a881a5496fa62b6d",
              "height": 300,
              "width": 300
            },
            {
              "url": "https://i.scdn.co/image/ab67616d0000485192f9a000a881a5496fa62b6d",
              "height": 64,
              "width": 64
            }
          ],
          "name": "Stay Down",
          "release_date": "1998-10-19",
          "release_date_precision": "day",
          "type": "album",
          "uri": "spotify:album:6UUJq06fTAr9H7xLiE1VFS",
          "album_group": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/33Ztukerf3He8FeKk5acn8"
              },
              "href": "https://api.spotify.com/v1/artists/33Ztukerf3He8FeKk5acn8",
              "id": "33Ztukerf3He8FeKk5acn8",
              "name": "Two Lone Swordsmen",
              "type": "artist",
              "uri": "spotify:artist:33Ztukerf3He8FeKk5acn8"
            }
          ]
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/33Ztukerf3He8FeKk5acn8"
            },
            "href": "https://api.spotify.com/v1/artists/33Ztukerf3He8FeKk5acn8",
            "id": "33Ztukerf3He8FeKk5acn8",
            "name": "Two Lone Swordsmen",
            "type": "artist",
            "uri": "spotify:artist:33Ztukerf3He8FeKk5acn8"
          }
        ],
        "available_markets": ["AR", "AU", "AT", "BE", "BO", "BR", "BG", "CA", "CL", "CO", "CR", "CY", "CZ", "DK", "DO", "DE", "EC", "EE", "SV", "FI", "FR", "GR", "GT", "HN", "HK", "HU", "IS", "IE", "IT", "LV", "LT", "LU", "MY", "MT", "MX", "NL", "NZ", "NI", "NO", "PA", "PY", "PE", "PH", "PL", "PT", "SG", "SK", "ES", "SE", "CH", "TW", "TR", "UY", "US", "GB", "AD", "LI", "MC", "ID", "JP", "TH", "VN", "RO", "IL", "ZA", "SA", "AE", "BH", "QA", "OM", "KW", "EG", "MA", "DZ", "TN", "LB", "JO", "PS", "IN", "BY", "KZ", "MD", "UA", "AL", "BA", "HR", "ME", "MK", "RS", "SI", "KR", "BD", "PK", "LK", "GH", "KE", "NG", "TZ", "UG", "AG", "AM", "BS", "BB", "BZ", "BT", "BW", "BF", "CV", "CW", "DM", "FJ", "GM", "GE", "GD", "GW", "GY", "HT", "JM", "KI", "LS", "LR", "MW", "MV", "ML", "MH", "FM", "NA", "NR", "NE", "PW", "PG", "WS", "SM", "ST", "SN", "SC", "SL", "SB", "KN", "LC", "VC", "SR", "TL", "TO", "TT", "TV", "VU", "AZ", "BN", "BI", "KH", "CM", "TD", "KM", "GQ", "SZ", "GA", "GN", "KG", "LA", "MO", "MR", "MN", "NP", "RW", "TG", "UZ", "ZW", "BJ", "MG", "MU", "MZ", "AO", "CI", "DJ", "ZM", "CD", "CG", "IQ", "LY", "TJ", "VE", "ET", "XC", "XK"],
        "disc_number": 1,
        "duration_ms": 143626,
        "explicit": false,
        "external_ids": {
          "isrc": "GBBPW9800091"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3xJW4rrff7M1jD8t1J5Dj0"
        },
        "href": "https://api.spotify.com/v1/tracks/3xJW4rrff7M1jD8t1J5Dj0",
        "id": "3xJW4rrff7M1jD8t1J5Dj0",
        "name": "Hope We Never Surface",
        "popularity": 34,
        "preview_url": "https://p.scdn.co/mp3-preview/e3cb7c629f36c2836dc09cb30fe789adc0444a87?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:3xJW4rrff7M1jD8t1J5Dj0",
        "is_local": false
      },
      {
        "album": {
          "album_type": "SINGLE",
          "total_tracks": 5,
          "available_markets": [],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4e0s9NinQo02X4exDDmW65"
          },
          "href": "https://api.spotify.com/v1/albums/4e0s9NinQo02X4exDDmW65",
          "id": "4e0s9NinQo02X4exDDmW65",
          "images": [
            {
              "url": "https://i.scdn.co/image/ab67616d0000b273410dd4054ccd5a57aba612d1",
              "height": 640,
              "width": 640
            },
            {
              "url": "https://i.scdn.co/image/ab67616d00001e02410dd4054ccd5a57aba612d1",
              "height": 300,
              "width": 300
            },
            {
              "url": "https://i.scdn.co/image/ab67616d00004851410dd4054ccd5a57aba612d1",
              "height": 64,
              "width": 64
            }
          ],
          "name": "TNGHT",
          "release_date": "2012-07-23",
          "release_date_precision": "day",
          "type": "album",
          "uri": "spotify:album:4e0s9NinQo02X4exDDmW65",
          "album_group": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/40jiZfvsiAi1aIarh5Z3d3"
              },
              "href": "https://api.spotify.com/v1/artists/40jiZfvsiAi1aIarh5Z3d3",
              "id": "40jiZfvsiAi1aIarh5Z3d3",
              "name": "TNGHT",
              "type": "artist",
              "uri": "spotify:artist:40jiZfvsiAi1aIarh5Z3d3"
            }
          ]
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/40jiZfvsiAi1aIarh5Z3d3"
            },
            "href": "https://api.spotify.com/v1/artists/40jiZfvsiAi1aIarh5Z3d3",
            "id": "40jiZfvsiAi1aIarh5Z3d3",
            "name": "TNGHT",
            "type": "artist",
            "uri": "spotify:artist:40jiZfvsiAi1aIarh5Z3d3"
          }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 199343,
        "explicit": false,
        "external_ids": {
          "isrc": "GBBPW1200114"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0Js9hB2I66nJliPIJxzn2R"
        },
        "href": "https://api.spotify.com/v1/tracks/0Js9hB2I66nJliPIJxzn2R",
        "id": "0Js9hB2I66nJliPIJxzn2R",
        "name": "Higher Ground",
        "popularity": 29,
        "preview_url": null,
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:0Js9hB2I66nJliPIJxzn2R",
        "is_local": false
      },
      {
        "album": {
          "album_type": "SINGLE",
          "total_tracks": 5,
          "available_markets": ["AD", "AE", "AG", "AL", "AM", "AO", "AR", "AT", "AU", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CD", "CG", "CH", "CI", "CL", "CM", "CO", "CR", "CV", "CW", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "ET", "FI", "FJ", "FM", "FR", "GA", "GB", "GD", "GE", "GH", "GM", "GN", "GQ", "GR", "GT", "GW", "GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IQ", "IS", "IT", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KR", "KW", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MN", "MO", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RW", "SA", "SB", "SC", "SE", "SG", "SI", "SK", "SL", "SM", "SN", "SR", "ST", "SV", "SZ", "TD", "TG", "TH", "TJ", "TL", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "UY", "UZ", "VC", "VE", "VN", "VU", "WS", "XK", "ZA", "ZM", "ZW"],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1kIkYRKKip01FVuJPoMtbR"
          },
          "href": "https://api.spotify.com/v1/albums/1kIkYRKKip01FVuJPoMtbR",
          "id": "1kIkYRKKip01FVuJPoMtbR",
          "images": [
            {
              "url": "https://i.scdn.co/image/ab67616d0000b27398528dc300fb2066ca913ebd",
              "height": 640,
              "width": 640
            },
            {
              "url": "https://i.scdn.co/image/ab67616d00001e0298528dc300fb2066ca913ebd",
              "height": 300,
              "width": 300
            },
            {
              "url": "https://i.scdn.co/image/ab67616d0000485198528dc300fb2066ca913ebd",
              "height": 64,
              "width": 64
            }
          ],
          "name": "The City",
          "release_date": "2012-10-08",
          "release_date_precision": "day",
          "type": "album",
          "uri": "spotify:album:1kIkYRKKip01FVuJPoMtbR",
          "album_group": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc"
              },
              "href": "https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc",
              "id": "4pb4rqWSoGUgxm63xmJ8xc",
              "name": "Madeon",
              "type": "artist",
              "uri": "spotify:artist:4pb4rqWSoGUgxm63xmJ8xc"
            }
          ]
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc"
            },
            "href": "https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc",
            "id": "4pb4rqWSoGUgxm63xmJ8xc",
            "name": "Madeon",
            "type": "artist",
            "uri": "spotify:artist:4pb4rqWSoGUgxm63xmJ8xc"
          }
        ],
        "available_markets": ["AR", "AU", "AT", "BE", "BO", "BR", "BG", "CA", "CL", "CO", "CR", "CY", "CZ", "DK", "DO", "DE", "EC", "EE", "SV", "FI", "FR", "GR", "GT", "HN", "HK", "HU", "IS", "IE", "IT", "LV", "LT", "LU", "MY", "MT", "MX", "NL", "NZ", "NI", "NO", "PA", "PY", "PE", "PH", "PL", "PT", "SG", "SK", "ES", "SE", "CH", "TW", "TR", "UY", "US", "GB", "AD", "LI", "MC", "ID", "JP", "TH", "VN", "RO", "IL", "ZA", "SA", "AE", "BH", "QA", "OM", "KW", "EG", "MA", "DZ", "TN", "LB", "JO", "PS", "IN", "BY", "KZ", "MD", "UA", "AL", "BA", "HR", "ME", "MK", "RS", "SI", "KR", "BD", "PK", "LK", "GH", "KE", "NG", "TZ", "UG", "AG", "AM", "BS", "BB", "BZ", "BT", "BW", "BF", "CV", "CW", "DM", "FJ", "GM", "GE", "GD", "GW", "GY", "HT", "JM", "KI", "LS", "LR", "MW", "MV", "ML", "MH", "FM", "NA", "NR", "NE", "PW", "PG", "WS", "SM", "ST", "SN", "SC", "SL", "SB", "KN", "LC", "VC", "SR", "TL", "TO", "TT", "TV", "VU", "AZ", "BN", "BI", "KH", "CM", "TD", "KM", "GQ", "SZ", "GA", "GN", "KG", "LA", "MO", "MR", "MN", "NP", "RW", "TG", "UZ", "ZW", "BJ", "MG", "MU", "MZ", "AO", "CI", "DJ", "ZM", "CD", "CG", "IQ", "LY", "TJ", "VE", "ET", "XK"],
        "disc_number": 1,
        "duration_ms": 233693,
        "explicit": false,
        "external_ids": {
          "isrc": "GBARL1201025"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/59iJua476fbi3PbddfPrez"
        },
        "href": "https://api.spotify.com/v1/tracks/59iJua476fbi3PbddfPrez",
        "id": "59iJua476fbi3PbddfPrez",
        "name": "The City",
        "popularity": 39,
        "preview_url": "https://p.scdn.co/mp3-preview/24ee1ad03d3c6b75fd52a6a9da450906414a30f4?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:59iJua476fbi3PbddfPrez",
        "is_local": false
      },
      {
        "album": {
          "album_type": "ALBUM",
          "total_tracks": 10,
          "available_markets": [],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7fnwsVgjeZgUeYqmGgkKSv"
          },
          "href": "https://api.spotify.com/v1/albums/7fnwsVgjeZgUeYqmGgkKSv",
          "id": "7fnwsVgjeZgUeYqmGgkKSv",
          "images": [
            {
              "url": "https://i.scdn.co/image/ab67616d0000b27372f35907dec345b2e7c6b315",
              "height": 640,
              "width": 640
            },
            {
              "url": "https://i.scdn.co/image/ab67616d00001e0272f35907dec345b2e7c6b315",
              "height": 300,
              "width": 300
            },
            {
              "url": "https://i.scdn.co/image/ab67616d0000485172f35907dec345b2e7c6b315",
              "height": 64,
              "width": 64
            }
          ],
          "name": "The Inner Mansions",
          "release_date": "2012-11-06",
          "release_date_precision": "day",
          "type": "album",
          "uri": "spotify:album:7fnwsVgjeZgUeYqmGgkKSv",
          "album_group": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2GE6MAdyGzeXpY9TwIYd3l"
              },
              "href": "https://api.spotify.com/v1/artists/2GE6MAdyGzeXpY9TwIYd3l",
              "id": "2GE6MAdyGzeXpY9TwIYd3l",
              "name": "Teen Daze",
              "type": "artist",
              "uri": "spotify:artist:2GE6MAdyGzeXpY9TwIYd3l"
            }
          ]
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2GE6MAdyGzeXpY9TwIYd3l"
            },
            "href": "https://api.spotify.com/v1/artists/2GE6MAdyGzeXpY9TwIYd3l",
            "id": "2GE6MAdyGzeXpY9TwIYd3l",
            "name": "Teen Daze",
            "type": "artist",
            "uri": "spotify:artist:2GE6MAdyGzeXpY9TwIYd3l"
          }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 434293,
        "explicit": false,
        "external_ids": {
          "isrc": "USZMA1200098"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0qsewl6nuPNW3GLinWRgvR"
        },
        "href": "https://api.spotify.com/v1/tracks/0qsewl6nuPNW3GLinWRgvR",
        "id": "0qsewl6nuPNW3GLinWRgvR",
        "name": "Discipleship",
        "popularity": 0,
        "preview_url": null,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:0qsewl6nuPNW3GLinWRgvR",
        "is_local": false
      },
      {
        "album": {
          "album_type": "ALBUM",
          "total_tracks": 12,
          "available_markets": ["AD", "AE", "AG", "AL", "AM", "AO", "AR", "AT", "AU", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CD", "CG", "CH", "CI", "CL", "CM", "CO", "CR", "CV", "CW", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "ET", "FI", "FJ", "FM", "FR", "GA", "GB", "GD", "GE", "GH", "GM", "GN", "GQ", "GR", "GT", "GW", "GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IQ", "IS", "IT", "JM", "JO", "KE", "KG", "KH", "KI", "KM", "KN", "KR", "KW", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MN", "MO", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RW", "SA", "SB", "SC", "SE", "SG", "SI", "SK", "SL", "SM", "SN", "SR", "ST", "SV", "SZ", "TD", "TG", "TH", "TJ", "TL", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "UY", "UZ", "VC", "VE", "VN", "VU", "WS", "XK", "ZA", "ZM", "ZW"],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1WwZwdTICfaZI51BIIEN9z"
          },
          "href": "https://api.spotify.com/v1/albums/1WwZwdTICfaZI51BIIEN9z",
          "id": "1WwZwdTICfaZI51BIIEN9z",
          "images": [
            {
              "url": "https://i.scdn.co/image/ab67616d0000b273d03dff7f5eeee485e5a45f62",
              "height": 640,
              "width": 640
            },
            {
              "url": "https://i.scdn.co/image/ab67616d00001e02d03dff7f5eeee485e5a45f62",
              "height": 300,
              "width": 300
            },
            {
              "url": "https://i.scdn.co/image/ab67616d00004851d03dff7f5eeee485e5a45f62",
              "height": 64,
              "width": 64
            }
          ],
          "name": "Crush",
          "release_date": "2019-10-18",
          "release_date_precision": "day",
          "type": "album",
          "uri": "spotify:album:1WwZwdTICfaZI51BIIEN9z",
          "album_group": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2AR42Ur9PcchQDtEdwkv4L"
              },
              "href": "https://api.spotify.com/v1/artists/2AR42Ur9PcchQDtEdwkv4L",
              "id": "2AR42Ur9PcchQDtEdwkv4L",
              "name": "Floating Points",
              "type": "artist",
              "uri": "spotify:artist:2AR42Ur9PcchQDtEdwkv4L"
            }
          ]
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2AR42Ur9PcchQDtEdwkv4L"
            },
            "href": "https://api.spotify.com/v1/artists/2AR42Ur9PcchQDtEdwkv4L",
            "id": "2AR42Ur9PcchQDtEdwkv4L",
            "name": "Floating Points",
            "type": "artist",
            "uri": "spotify:artist:2AR42Ur9PcchQDtEdwkv4L"
          }
        ],
        "available_markets": ["AR", "AU", "AT", "BE", "BO", "BR", "BG", "CA", "CL", "CO", "CR", "CY", "CZ", "DK", "DO", "DE", "EC", "EE", "SV", "FI", "FR", "GR", "GT", "HN", "HK", "HU", "IS", "IE", "IT", "LV", "LT", "LU", "MY", "MT", "MX", "NL", "NZ", "NI", "NO", "PA", "PY", "PE", "PH", "PL", "PT", "SG", "SK", "ES", "SE", "CH", "TW", "TR", "UY", "US", "GB", "AD", "LI", "MC", "ID", "TH", "VN", "RO", "IL", "ZA", "SA", "AE", "BH", "QA", "OM", "KW", "EG", "MA", "DZ", "TN", "LB", "JO", "PS", "IN", "BY", "KZ", "MD", "UA", "AL", "BA", "HR", "ME", "MK", "RS", "SI", "KR", "BD", "PK", "LK", "GH", "KE", "NG", "TZ", "UG", "AG", "AM", "BS", "BB", "BZ", "BT", "BW", "BF", "CV", "CW", "DM", "FJ", "GM", "GE", "GD", "GW", "GY", "HT", "JM", "KI", "LS", "LR", "MW", "MV", "ML", "MH", "FM", "NA", "NR", "NE", "PW", "PG", "WS", "SM", "ST", "SN", "SC", "SL", "SB", "KN", "LC", "VC", "SR", "TL", "TO", "TT", "TV", "VU", "AZ", "BN", "BI", "KH", "CM", "TD", "KM", "GQ", "SZ", "GA", "GN", "KG", "LA", "MO", "MR", "MN", "NP", "RW", "TG", "UZ", "ZW", "BJ", "MG", "MU", "MZ", "AO", "CI", "DJ", "ZM", "CD", "CG", "IQ", "LY", "TJ", "VE", "ET", "XK"],
        "disc_number": 1,
        "duration_ms": 281141,
        "explicit": false,
        "external_ids": {
          "isrc": "GBCFB1900139"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3PhICIIH9dua2ZZryHqiHE"
        },
        "href": "https://api.spotify.com/v1/tracks/3PhICIIH9dua2ZZryHqiHE",
        "id": "3PhICIIH9dua2ZZryHqiHE",
        "name": "LesAlpx",
        "popularity": 38,
        "preview_url": "https://p.scdn.co/mp3-preview/b2e4c5146e228f342553825bafb2ba903b527069?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:3PhICIIH9dua2ZZryHqiHE",
        "is_local": false
      }
    ]
  }},

  {"playlistName": "test 2", "list":
  {
    "tracks": [
      {
        "album": {
          "album_group": "ALBUM",
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/57dN52uHvrHOxijzpIgu3E"
              },
              "href": "https://api.spotify.com/v1/artists/57dN52uHvrHOxijzpIgu3E",
              "id": "57dN52uHvrHOxijzpIgu3E",
              "name": "Ratatat",
              "type": "artist",
              "uri": "spotify:artist:57dN52uHvrHOxijzpIgu3E"
            }
          ],
          "available_markets": [],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/2n5wpk7KaHpp3mgUYqpF4f"
          },
          "href": "https://api.spotify.com/v1/albums/2n5wpk7KaHpp3mgUYqpF4f",
          "id": "2n5wpk7KaHpp3mgUYqpF4f",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273dcd3381d0213c26dd278e81c",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02dcd3381d0213c26dd278e81c",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851dcd3381d0213c26dd278e81c",
              "width": 64
            }
          ],
          "name": "Classics",
          "release_date": "2006-08-22",
          "release_date_precision": "day",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:2n5wpk7KaHpp3mgUYqpF4f"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/57dN52uHvrHOxijzpIgu3E"
            },
            "href": "https://api.spotify.com/v1/artists/57dN52uHvrHOxijzpIgu3E",
            "id": "57dN52uHvrHOxijzpIgu3E",
            "name": "Ratatat",
            "type": "artist",
            "uri": "spotify:artist:57dN52uHvrHOxijzpIgu3E"
          }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 260173,
        "explicit": false,
        "external_ids": {
          "isrc": "GBBKS0600037"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4EBisBBehGON4ESJsNZBsP"
        },
        "href": "https://api.spotify.com/v1/tracks/4EBisBBehGON4ESJsNZBsP",
        "id": "4EBisBBehGON4ESJsNZBsP",
        "is_local": false,
        "name": "Wildcat",
        "popularity": 0,
        "preview_url": null,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:4EBisBBehGON4ESJsNZBsP"
      },
      {
        "album": {
          "album_group": "SINGLE",
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5he5w2lnU9x7JFhnwcekXX"
              },
              "href": "https://api.spotify.com/v1/artists/5he5w2lnU9x7JFhnwcekXX",
              "id": "5he5w2lnU9x7JFhnwcekXX",
              "name": "Skrillex",
              "type": "artist",
              "uri": "spotify:artist:5he5w2lnU9x7JFhnwcekXX"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5XJ2NeBxZP3HFM8VoBQEUe"
          },
          "href": "https://api.spotify.com/v1/albums/5XJ2NeBxZP3HFM8VoBQEUe",
          "id": "5XJ2NeBxZP3HFM8VoBQEUe",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2736081278cb62df2757d55633b",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e026081278cb62df2757d55633b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048516081278cb62df2757d55633b",
              "width": 64
            }
          ],
          "name": "Bangarang EP",
          "release_date": "2011-12-27",
          "release_date_precision": "day",
          "total_tracks": 8,
          "type": "album",
          "uri": "spotify:album:5XJ2NeBxZP3HFM8VoBQEUe"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5he5w2lnU9x7JFhnwcekXX"
            },
            "href": "https://api.spotify.com/v1/artists/5he5w2lnU9x7JFhnwcekXX",
            "id": "5he5w2lnU9x7JFhnwcekXX",
            "name": "Skrillex",
            "type": "artist",
            "uri": "spotify:artist:5he5w2lnU9x7JFhnwcekXX"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 180400,
        "explicit": false,
        "external_ids": {
          "isrc": "USAT21104242"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1LV5G400jD3Ytvyv6Dlkym"
        },
        "href": "https://api.spotify.com/v1/tracks/1LV5G400jD3Ytvyv6Dlkym",
        "id": "1LV5G400jD3Ytvyv6Dlkym",
        "is_local": false,
        "name": "Right In",
        "popularity": 50,
        "preview_url": "https://p.scdn.co/mp3-preview/584268d3269377ce37845e27a8f8beca06d069e0?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1LV5G400jD3Ytvyv6Dlkym"
      },
      {
        "album": {
          "album_group": "SINGLE",
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2CIMQHirSU0MQqyYHq0eOx"
              },
              "href": "https://api.spotify.com/v1/artists/2CIMQHirSU0MQqyYHq0eOx",
              "id": "2CIMQHirSU0MQqyYHq0eOx",
              "name": "deadmau5",
              "type": "artist",
              "uri": "spotify:artist:2CIMQHirSU0MQqyYHq0eOx"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6EYy8giXumFOmT1fpZTCMB"
          },
          "href": "https://api.spotify.com/v1/albums/6EYy8giXumFOmT1fpZTCMB",
          "id": "6EYy8giXumFOmT1fpZTCMB",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273ac4c76801e5286f371b5f4b1",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02ac4c76801e5286f371b5f4b1",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851ac4c76801e5286f371b5f4b1",
              "width": 64
            }
          ],
          "name": "Strobe",
          "release_date": "2010-01-01",
          "release_date_precision": "day",
          "total_tracks": 6,
          "type": "album",
          "uri": "spotify:album:6EYy8giXumFOmT1fpZTCMB"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2CIMQHirSU0MQqyYHq0eOx"
            },
            "href": "https://api.spotify.com/v1/artists/2CIMQHirSU0MQqyYHq0eOx",
            "id": "2CIMQHirSU0MQqyYHq0eOx",
            "name": "deadmau5",
            "type": "artist",
            "uri": "spotify:artist:2CIMQHirSU0MQqyYHq0eOx"
          }
        ],
        "available_markets": [
          "AR",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "NL",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 634151,
        "explicit": false,
        "external_ids": {
          "isrc": "GBTDG0900141"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4kJWtxDDNb9oAk3h7sX3N4"
        },
        "href": "https://api.spotify.com/v1/tracks/4kJWtxDDNb9oAk3h7sX3N4",
        "id": "4kJWtxDDNb9oAk3h7sX3N4",
        "is_local": false,
        "name": "Strobe",
        "popularity": 44,
        "preview_url": null,
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:4kJWtxDDNb9oAk3h7sX3N4"
      },
      {
        "album": {
          "album_group": "ALBUM",
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/23MIhFHpoOuhtEHZDrrnCS"
              },
              "href": "https://api.spotify.com/v1/artists/23MIhFHpoOuhtEHZDrrnCS",
              "id": "23MIhFHpoOuhtEHZDrrnCS",
              "name": "The Field",
              "type": "artist",
              "uri": "spotify:artist:23MIhFHpoOuhtEHZDrrnCS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6h1LdVhHDirAXwgDFftCL0"
          },
          "href": "https://api.spotify.com/v1/albums/6h1LdVhHDirAXwgDFftCL0",
          "id": "6h1LdVhHDirAXwgDFftCL0",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273d58054a18b7c1ea4e6877cf7",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02d58054a18b7c1ea4e6877cf7",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851d58054a18b7c1ea4e6877cf7",
              "width": 64
            }
          ],
          "name": "Looping State Of Mind",
          "release_date": "2011-09-05",
          "release_date_precision": "day",
          "total_tracks": 7,
          "type": "album",
          "uri": "spotify:album:6h1LdVhHDirAXwgDFftCL0"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/23MIhFHpoOuhtEHZDrrnCS"
            },
            "href": "https://api.spotify.com/v1/artists/23MIhFHpoOuhtEHZDrrnCS",
            "id": "23MIhFHpoOuhtEHZDrrnCS",
            "name": "The Field",
            "type": "artist",
            "uri": "spotify:artist:23MIhFHpoOuhtEHZDrrnCS"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XC",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 558650,
        "explicit": false,
        "external_ids": {
          "isrc": "DEU671100156"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0Uhfl92W8pbJmh2zyxJE0u"
        },
        "href": "https://api.spotify.com/v1/tracks/0Uhfl92W8pbJmh2zyxJE0u",
        "id": "0Uhfl92W8pbJmh2zyxJE0u",
        "is_local": false,
        "name": "It´s Up There",
        "popularity": 26,
        "preview_url": "https://p.scdn.co/mp3-preview/2b41c50ffc5c033681f4f431308f91d6e584f6ff?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:0Uhfl92W8pbJmh2zyxJE0u"
      },
      {
        "album": {
          "album_group": "ALBUM",
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2qhmNI4ZHPpeDutdg473Z3"
              },
              "href": "https://api.spotify.com/v1/artists/2qhmNI4ZHPpeDutdg473Z3",
              "id": "2qhmNI4ZHPpeDutdg473Z3",
              "name": "The Future Sound Of London",
              "type": "artist",
              "uri": "spotify:artist:2qhmNI4ZHPpeDutdg473Z3"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/2xHvAxrgMfKrYIicQVT9ay"
          },
          "href": "https://api.spotify.com/v1/albums/2xHvAxrgMfKrYIicQVT9ay",
          "id": "2xHvAxrgMfKrYIicQVT9ay",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273d94474e20a0d381ff8e59dff",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02d94474e20a0d381ff8e59dff",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851d94474e20a0d381ff8e59dff",
              "width": 64
            }
          ],
          "name": "Dead Cities",
          "release_date": "1996-01-01",
          "release_date_precision": "day",
          "total_tracks": 13,
          "type": "album",
          "uri": "spotify:album:2xHvAxrgMfKrYIicQVT9ay"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2qhmNI4ZHPpeDutdg473Z3"
            },
            "href": "https://api.spotify.com/v1/artists/2qhmNI4ZHPpeDutdg473Z3",
            "id": "2qhmNI4ZHPpeDutdg473Z3",
            "name": "The Future Sound Of London",
            "type": "artist",
            "uri": "spotify:artist:2qhmNI4ZHPpeDutdg473Z3"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 379160,
        "explicit": false,
        "external_ids": {
          "isrc": "GBAAA9600234"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0VNfwqLDcbKk5eDBOdYWTI"
        },
        "href": "https://api.spotify.com/v1/tracks/0VNfwqLDcbKk5eDBOdYWTI",
        "id": "0VNfwqLDcbKk5eDBOdYWTI",
        "is_local": false,
        "name": "We Have Explosive",
        "popularity": 34,
        "preview_url": null,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:0VNfwqLDcbKk5eDBOdYWTI"
      }
    ],
    "seeds": [
      {
        "initialPoolSize": 500,
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "id": "6WH1V41LwGDGmlPUhSZLHO",
        "type": "ARTIST",
        "href": "https://api.spotify.com/v1/artists/6WH1V41LwGDGmlPUhSZLHO"
      },
      {
        "initialPoolSize": 500,
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "id": "33zDGjUK3BiqgFxoIpUWLy",
        "type": "TRACK",
        "href": "https://api.spotify.com/v1/tracks/33zDGjUK3BiqgFxoIpUWLy"
      },
      {
        "initialPoolSize": 1000,
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "id": "electronic",
        "type": "GENRE",
        "href": null
      }
    ]
  }},

{"playlistName": "test 3", "list":
{
    "tracks": [
      {
        "album": {
          "album_group": "SINGLE",
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3sb3yLRnhW2L2ulU93eKfl"
              },
              "href": "https://api.spotify.com/v1/artists/3sb3yLRnhW2L2ulU93eKfl",
              "id": "3sb3yLRnhW2L2ulU93eKfl",
              "name": "Beacon",
              "type": "artist",
              "uri": "spotify:artist:3sb3yLRnhW2L2ulU93eKfl"
            }
          ],
          "available_markets": [],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1frJAaS8PwWZ34Ex3RVQTu"
          },
          "href": "https://api.spotify.com/v1/albums/1frJAaS8PwWZ34Ex3RVQTu",
          "id": "1frJAaS8PwWZ34Ex3RVQTu",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/8b415d826fdf9b25c7195bd8be9e52a8f24f438e",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/e097c7004bdce6273a48b238d8c15300c62bb5d2",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/799722380d3f3d016a6c298b42fd783d3699f7b2",
              "width": 64
            }
          ],
          "name": "For Now",
          "release_date": "2012-10-02",
          "release_date_precision": "day",
          "total_tracks": 5,
          "type": "album",
          "uri": "spotify:album:1frJAaS8PwWZ34Ex3RVQTu"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3sb3yLRnhW2L2ulU93eKfl"
            },
            "href": "https://api.spotify.com/v1/artists/3sb3yLRnhW2L2ulU93eKfl",
            "id": "3sb3yLRnhW2L2ulU93eKfl",
            "name": "Beacon",
            "type": "artist",
            "uri": "spotify:artist:3sb3yLRnhW2L2ulU93eKfl"
          }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 192083,
        "explicit": false,
        "external_ids": {
          "isrc": "US2J71206904"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7dP4Rx8rkk9gwVubpEmQcY"
        },
        "href": "https://api.spotify.com/v1/tracks/7dP4Rx8rkk9gwVubpEmQcY",
        "id": "7dP4Rx8rkk9gwVubpEmQcY",
        "is_local": false,
        "name": "Feeling's Gone",
        "popularity": 0,
        "preview_url": null,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:7dP4Rx8rkk9gwVubpEmQcY"
      },
      {
        "album": {
          "album_group": "ALBUM",
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/23MIhFHpoOuhtEHZDrrnCS"
              },
              "href": "https://api.spotify.com/v1/artists/23MIhFHpoOuhtEHZDrrnCS",
              "id": "23MIhFHpoOuhtEHZDrrnCS",
              "name": "The Field",
              "type": "artist",
              "uri": "spotify:artist:23MIhFHpoOuhtEHZDrrnCS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6h1LdVhHDirAXwgDFftCL0"
          },
          "href": "https://api.spotify.com/v1/albums/6h1LdVhHDirAXwgDFftCL0",
          "id": "6h1LdVhHDirAXwgDFftCL0",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273d58054a18b7c1ea4e6877cf7",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02d58054a18b7c1ea4e6877cf7",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851d58054a18b7c1ea4e6877cf7",
              "width": 64
            }
          ],
          "name": "Looping State Of Mind",
          "release_date": "2011-09-05",
          "release_date_precision": "day",
          "total_tracks": 7,
          "type": "album",
          "uri": "spotify:album:6h1LdVhHDirAXwgDFftCL0"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/23MIhFHpoOuhtEHZDrrnCS"
            },
            "href": "https://api.spotify.com/v1/artists/23MIhFHpoOuhtEHZDrrnCS",
            "id": "23MIhFHpoOuhtEHZDrrnCS",
            "name": "The Field",
            "type": "artist",
            "uri": "spotify:artist:23MIhFHpoOuhtEHZDrrnCS"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XC",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 519013,
        "explicit": false,
        "external_ids": {
          "isrc": "DEU671100155"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0Q70gojAQn9mTAdY15tWzM"
        },
        "href": "https://api.spotify.com/v1/tracks/0Q70gojAQn9mTAdY15tWzM",
        "id": "0Q70gojAQn9mTAdY15tWzM",
        "is_local": false,
        "name": "Is This Power",
        "popularity": 35,
        "preview_url": "https://p.scdn.co/mp3-preview/7080334dd22c473ff7ba1b0f464c2d808db70587?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:0Q70gojAQn9mTAdY15tWzM"
      },
      {
        "album": {
          "album_group": "SINGLE",
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4L94lx80QBByxCJ3ZUHIEL"
              },
              "href": "https://api.spotify.com/v1/artists/4L94lx80QBByxCJ3ZUHIEL",
              "id": "4L94lx80QBByxCJ3ZUHIEL",
              "name": "Gang Colours",
              "type": "artist",
              "uri": "spotify:artist:4L94lx80QBByxCJ3ZUHIEL"
            }
          ],
          "available_markets": [],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0AhP6c7n5H7SPKWMDkE6f3"
          },
          "href": "https://api.spotify.com/v1/albums/0AhP6c7n5H7SPKWMDkE6f3",
          "id": "0AhP6c7n5H7SPKWMDkE6f3",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273c660a7d42025154461b5f2b1",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02c660a7d42025154461b5f2b1",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851c660a7d42025154461b5f2b1",
              "width": 64
            }
          ],
          "name": "Fancy Restaurant",
          "release_date": "2012-02-19",
          "release_date_precision": "day",
          "total_tracks": 4,
          "type": "album",
          "uri": "spotify:album:0AhP6c7n5H7SPKWMDkE6f3"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4L94lx80QBByxCJ3ZUHIEL"
            },
            "href": "https://api.spotify.com/v1/artists/4L94lx80QBByxCJ3ZUHIEL",
            "id": "4L94lx80QBByxCJ3ZUHIEL",
            "name": "Gang Colours",
            "type": "artist",
            "uri": "spotify:artist:4L94lx80QBByxCJ3ZUHIEL"
          }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 179880,
        "explicit": false,
        "external_ids": {
          "isrc": "GBMEF1100396"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/75VkjFedcGu8MRb50IEblM"
        },
        "href": "https://api.spotify.com/v1/tracks/75VkjFedcGu8MRb50IEblM",
        "id": "75VkjFedcGu8MRb50IEblM",
        "is_local": false,
        "name": "Fancy Restaurant",
        "popularity": 0,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:75VkjFedcGu8MRb50IEblM"
      },
      {
        "album": {
          "album_group": "ALBUM",
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3IUSkU24GuugkT7GDUlP9b"
              },
              "href": "https://api.spotify.com/v1/artists/3IUSkU24GuugkT7GDUlP9b",
              "id": "3IUSkU24GuugkT7GDUlP9b",
              "name": "Mark Fell",
              "type": "artist",
              "uri": "spotify:artist:3IUSkU24GuugkT7GDUlP9b"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/49bi4Ch9Ip1cIQuevzyU2V"
              },
              "href": "https://api.spotify.com/v1/artists/49bi4Ch9Ip1cIQuevzyU2V",
              "id": "49bi4Ch9Ip1cIQuevzyU2V",
              "name": "Gábor Lázár",
              "type": "artist",
              "uri": "spotify:artist:49bi4Ch9Ip1cIQuevzyU2V"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4MDRlvmhqupeyV1FD4Axgk"
          },
          "href": "https://api.spotify.com/v1/albums/4MDRlvmhqupeyV1FD4Axgk",
          "id": "4MDRlvmhqupeyV1FD4Axgk",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273fdc59dcc27b7be0e560e82f4",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02fdc59dcc27b7be0e560e82f4",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851fdc59dcc27b7be0e560e82f4",
              "width": 64
            }
          ],
          "name": "The Neurobiology of Moral Decision Making",
          "release_date": "2015-06-29",
          "release_date_precision": "day",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:4MDRlvmhqupeyV1FD4Axgk"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3IUSkU24GuugkT7GDUlP9b"
            },
            "href": "https://api.spotify.com/v1/artists/3IUSkU24GuugkT7GDUlP9b",
            "id": "3IUSkU24GuugkT7GDUlP9b",
            "name": "Mark Fell",
            "type": "artist",
            "uri": "spotify:artist:3IUSkU24GuugkT7GDUlP9b"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/49bi4Ch9Ip1cIQuevzyU2V"
            },
            "href": "https://api.spotify.com/v1/artists/49bi4Ch9Ip1cIQuevzyU2V",
            "id": "49bi4Ch9Ip1cIQuevzyU2V",
            "name": "Gábor Lázár",
            "type": "artist",
            "uri": "spotify:artist:49bi4Ch9Ip1cIQuevzyU2V"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 104348,
        "explicit": false,
        "external_ids": {
          "isrc": "USA2Z1510823"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2Jm8qRjOTPFbfTCkdRANIY"
        },
        "href": "https://api.spotify.com/v1/tracks/2Jm8qRjOTPFbfTCkdRANIY",
        "id": "2Jm8qRjOTPFbfTCkdRANIY",
        "is_local": false,
        "name": "Untitled 1",
        "popularity": 10,
        "preview_url": "https://p.scdn.co/mp3-preview/10e8bca1c595163e84080eb472f1191a694e5f77?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:2Jm8qRjOTPFbfTCkdRANIY"
      },
      {
        "album": {
          "album_group": "ALBUM",
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/65EXuYHVoehCKqp0kOS6px"
              },
              "href": "https://api.spotify.com/v1/artists/65EXuYHVoehCKqp0kOS6px",
              "id": "65EXuYHVoehCKqp0kOS6px",
              "name": "Parov Stelar",
              "type": "artist",
              "uri": "spotify:artist:65EXuYHVoehCKqp0kOS6px"
            }
          ],
          "available_markets": [],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5YCKjXrzZzgbjEYlZekh6N"
          },
          "href": "https://api.spotify.com/v1/albums/5YCKjXrzZzgbjEYlZekh6N",
          "id": "5YCKjXrzZzgbjEYlZekh6N",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27345ddcb7eab7ecf7780eecfb1",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0245ddcb7eab7ecf7780eecfb1",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485145ddcb7eab7ecf7780eecfb1",
              "width": 64
            }
          ],
          "name": "Coco Part 2",
          "release_date": "2009-09-14",
          "release_date_precision": "day",
          "total_tracks": 13,
          "type": "album",
          "uri": "spotify:album:5YCKjXrzZzgbjEYlZekh6N"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/65EXuYHVoehCKqp0kOS6px"
            },
            "href": "https://api.spotify.com/v1/artists/65EXuYHVoehCKqp0kOS6px",
            "id": "65EXuYHVoehCKqp0kOS6px",
            "name": "Parov Stelar",
            "type": "artist",
            "uri": "spotify:artist:65EXuYHVoehCKqp0kOS6px"
          }
        ],
        "available_markets": [],
        "disc_number": 1,
        "duration_ms": 243870,
        "explicit": false,
        "external_ids": {
          "isrc": "ATE610800063"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1n633WUCp9jOwrgaJBACxO"
        },
        "href": "https://api.spotify.com/v1/tracks/1n633WUCp9jOwrgaJBACxO",
        "id": "1n633WUCp9jOwrgaJBACxO",
        "is_local": false,
        "name": "Libella Swing",
        "popularity": 0,
        "preview_url": null,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:1n633WUCp9jOwrgaJBACxO"
      }
    ],
    "seeds": [
      {
        "initialPoolSize": 500,
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "id": "6WH1V41LwGDGmlPUhSZLHO",
        "type": "ARTIST",
        "href": "https://api.spotify.com/v1/artists/6WH1V41LwGDGmlPUhSZLHO"
      },
      {
        "initialPoolSize": 500,
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "id": "33zDGjUK3BiqgFxoIpUWLy",
        "type": "TRACK",
        "href": "https://api.spotify.com/v1/tracks/33zDGjUK3BiqgFxoIpUWLy"
      },
      {
        "initialPoolSize": 1000,
        "afterFilteringSize": 417,
        "afterRelinkingSize": 417,
        "id": "electronic",
        "type": "GENRE",
        "href": null
      }
    ]
  }}]