"""empty message

Revision ID: abdd46c3e782
Revises: d9d985180ba5
Create Date: 2023-04-12 11:25:04.791355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdd46c3e782'
down_revision = 'd9d985180ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('image_thumb_url')
        batch_op.drop_column('artist_spotify_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_spotify_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_thumb_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
